sudo: required

language: java
script: mvn install
deploy:
  provider: releases
  skip-cleanup: true
  api_key: $GITHUB_TOKEN
  github-token: $GITHUB_TOKEN
  keep-history: true
  file: target/*
  file_glob: true
  on:
    branch: master
	
services: docker
  
before_install: docker build -t mcarville/rubiks .