sudo: required
services: docker
language: java
before_install: export GIT_COMMIT_BRANCH=$(git rev-parse --abbrev-ref HEAD) && echo $GIT_COMMIT_BRANCH && export GIT_COMMIT_ID=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p') && echo $GIT_COMMIT_ID && export DOCKET_TAG_NAME="rubiks."$GIT_COMMIT_BRANCH"."$GIT_COMMIT_ID && echo $DOCKET_TAG_NAME
script: mvn install
deploy:
  provider: releases
  skip-cleanup: true
  api_key: $GITHUB_TOKEN
  github-token: $GITHUB_TOKEN
  keep-history: true
  file: target/*
  file_glob: true
  on:
    branch: master
after_success: docker build -t mcarville/sandbox:$DOCKET_TAG_NAME .
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master