sudo: required
services: docker
language: java
before_install: 
  provider: script
  script: bash docker_init
  on:
    branch: master
script: mvn install
deploy:
  provider: releases
  skip-cleanup: true
  api_key: $GITHUB_TOKEN
  github-token: $GITHUB_TOKEN
  keep-history: true
  file: war/target/*
  file_glob: true
  on:
    branch: master
after_success: docker build -t mcarville/sandbox:$DOCKET_TAG_NAME .
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
	