sudo: required
services: docker
language: java
script: mvn install
deploy:
  provider: releases
  skip-cleanup: true
  api_key: $GITHUB_TOKEN
  github-token: $GITHUB_TOKEN
  keep-history: true
  file: target/*
  file_glob: true
  on:
    branch: master
deploy: docker build -t mcarville/rubiks .