sudo: required
services: docker
language: java
before_install: export GIT_COMMIT_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi) && echo $GIT_COMMIT_BRANCH && export GIT_COMMIT_ID=$(git rev-parse --short HEAD) && echo $GIT_COMMIT_ID && export GIT_VERSION_TAG=$GIT_COMMIT_BRANCH"."$GIT_COMMIT_ID && echo $GIT_VERSION_TAG && bash docker_init
script: mvn install
deploy:
  provider: releases
  skip-cleanup: true
  api_key: $GITHUB_TOKEN
  github-token: $GITHUB_TOKEN
  keep-history: true
  file: war/target/*
  file_glob: true
  on:
    branch: master
after_success: bash docker_build && bash <(curl -s https://codecov.io/bash) -t a405876d-a14e-42d5-944e-71e8b8652d20
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
