#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push mcarville/sandbox:rubiks-gui:latest
docker push mcarville/sandbox:rubiks-gui:$GIT_VERSION_TAG
docker push mcarville/sandbox:rubiks-cube-robot:latest
docker push mcarville/sandbox:rubiks-cube-robot:$GIT_VERSION_TAG
docker push mcarville/sandbox:elasticsearch-gui:latest
docker push mcarville/sandbox:elasticsearch-gui:$GIT_VERSION_TAG