#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker run -itd -p 9092:9092 -p 9000:9000 -e KAFKA_ADVERTISED_HOST_NAME=127.0.0.1 mcarville/sandbox:ha_kafka_5