#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
for IMAGE_NAME in "war" "rubiks-cube-robot" "elastic-gui"
do
	docker push mcarville/sandbox:${IMAGE_NAME}.$GIT_VERSION_TAG
	docker push mcarville/sandbox:${IMAGE_NAME}.latest
done